### ISSUE TITLE
L540 support

### ISSUE THREAD

**Issue by BangL** [thrimbor/thinkpad-uefi-sign#1]
hey!
i tried using this on my L540, but it did not work and continued to beep after signing my custom rom.

i then verified my original unmodified rom, which i extracted from the device before tinkering with it. this is the result:
```
❯ ./verify.py /mnt/Storage/Nextcloud/LenovoL540Bios/mybios/L540original_1.rom
INFO: Found public key modulus at offset  0x7aed16
INFO: TCPA block found at offset  0x6c3a00
INFO: Volume offset: 0
INFO: Volume size: 2686976
ERROR: TCPA volume hash mismatch
  TCPA volume hash: 04fd6debcdf6d9dd3ecba3e799ee21435e0fef4e
Actual volume hash: 2717cd0ff9c657e98b1f89cd12f64e5a0b08db43

SIGNATURES INCORRECT!
```

so, it seems like the signature check on L540 differs from other devices somehow.
any chance to provide support for L540 as well?

**Comment by BangL** [comment]
this is my original rom with an actual valid signature: **link removed**, which gives me a false "SIGNATURES INCORRECT!" with your tool.

and this is my modded rom file with an invalid signature, which i would like to sign: **link removed**

would be awesome if you could use this to debug, so i can get a properly signed and therefore beep-less modded flash onto my device as well <3

**Comment by thrimbor** [comment]
Hi,
I think I figured out what the problem is, and opened PR #2 with what I think is the correct fix. I don't own an L540 myself, so please leave feedback whether it worked for you.

**Comment by BangL** [comment]
tested and confirmed! booting absolutely beepfree now :)
thank you so much <3
